### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by caiohasouza** [bi4o4ek/puppet-opendkim#4]
Hello, I am trying to set some parameters in Opendkim but am finding syntax error, my code:

{ class 'opendkim':
     Mode => 's',
}

And I get this error:
"Error: Could not retrieve catalog from remote server: Error 400 on Server: Could not parse for environment production: Syntax error at 'Mode'; expected '}' at /etc/puppet/nodes/server.pp:4 on node server.local
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run"

Thank you in advance your attention

**Comment by bi4o4ek** [comment]
Read init.pp please and try to use something like this
{ class 'opendkim':
     mode => 's',
}

**Comment by caiohasouza** [comment]
Hello,

Right, You did as you passed and follows the error:

Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Could not parse for environment production: Syntax error at '{'; expected '}' at /etc/puppet/nodes/server.pp:217 on node server.local
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run

Att;

**Comment by bi4o4ek** [comment]
Sorry. Improperly located brace.
Try this
class { 'opendkim':
  mode => 's',
}

**Comment by caiohasouza** [comment]
Ok, 

Let's go:

Case 1:
  class { 'opendkim':
    mode => 's',
  }
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Invalid parameter mode on Class[Opendkim] at /etc/puppet/nodes/server.pp:216 on node server.local
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run

###################################################################

Case 2:
  class { 'opendkim':
    Mode => 's',
  }
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Could not parse for environment production: Syntax error at 'Mode'; expected '}' at /etc/puppet/nodes/server.pp:215 on node server.local
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run

Att;

**Comment by bi4o4ek** [comment]
Execute 'git pull' at the repo with this module.
What is your puppet version?

**Comment by caiohasouza** [comment]
I have instaled from puppet forge (bi4o4ek-opendkim (v0.0.5))

Puppet 3.8.2.

Att;

**Comment by bi4o4ek** [comment]
Try to use latest version from github
